### ISSUE TITLE
Add acceptance test for "accept unknown fields in response"

### ISSUE THREAD

**Issue by dnephin** [Yelp/bravado#111]
If the client receives extra data in the response, it should not raise an error.  A service should be able to add extra fields to its response object without having to do a api version bump, as long as the old fields are unmodified.

This has the potential to create a lot of failures. I don't believe there is a test for this in `swagger-py`, but we should verify it works correct in `bravado` before release.

**Comment by prat0318** [comment]
+1 for a test. I manually tested and currently swaggerpy silently ignores the extra fields.

**Comment by dnephin** [comment]
Awesome, thanks for testing it out!

**Comment by analogue** [comment]
[Unit test] (https://github.com/Yelp/bravado-core/blob/master/tests/unmarshal/unmarshal_object_test.py#L173) for this exists.
