### ISSUE TITLE
Don't error when the server returns extra response fields

### ISSUE THREAD

**Issue by dnephin** [Yelp/bravado#146]
We chatted a bit about this today. I still want to write a test for it, but I won't have time to do that for the next couple of weeks, so I wanted to get it documented here.

A service will need to change its API. API changes need to be backwards compatible, or increase the version number (while still providing the old version).  In the case where an endpoint is only adding more data to the response, we shouldn't need to increase the endpoint version number.  Clients should be fine to ignore any unexpected fields.

**Comment by dnephin** [comment]
I think this goes along with [the Robustness_principle](http://en.wikipedia.org/wiki/Robustness_principle).

The client needs to be strict about what it sends the server, but it should be liberal about what it accepts. Extra fields that it doesn't know about are ok, it can just ignore them.

One solution might be to add a new config value to bravado_core, which would enable this behaviour, and we could default it to True for the client.

I'll try to write up a test for this case sometime soon.

**Comment by bwbaugh** [comment]
Has the behavior been manually tested yet? I was under the impression that any field not in the api-docs was silently ignored by the client.

**Comment by dnephin** [comment]
Working on a test case now. That was the behaviour in swagger-py, but bravado is a lot more strict about these things.

**Comment by dnephin** [comment]
Ok, this seems to be working correctly. If a model is used, the response type is the model with the correct fields. If an object response type is used, the response will contain all the fields.

It makes me wonder if the service validation will pass with extra unknown fields.

**Comment by analogue** [comment]
After re-reading the jsonschema spec, it does say that when the additionalProperties value is not present, it defaults to an empty schema, hence accepts everything.  My memory is failing me :-(

http://json-schema.org/latest/json-schema-validation.html

5.4.4.3.  Default values

If either "properties" or "patternProperties" are absent, they can be considered present with an empty object as a value.

If "additionalProperties" is absent, it may be considered present with an empty schema as a value.

**Comment by dnephin** [comment]
https://github.com/Yelp/bravado/compare/master...dnephin:test_unknown_fields is what I was working on

**Comment by analogue** [comment]
A unit test that verifies this behavior exists [here](https://github.com/Yelp/bravado-core/blob/master/tests/unmarshal/unmarshal_object_test.py#L173).
