### ISSUE TITLE
`_request_options` not available now.

### ISSUE THREAD

**Issue by prat0318** [Yelp/bravado#151]
Backwards compatibility with swaggerpy breaks as `_request_options` is not accepted in bravado:
```
swagger_client.pet.addPet(
    body=pet,
    _request_options={"headers": {"foo": "bar"}},
).result()
```
should add the additional header to the request.

**Comment by analogue** [comment]
Works fine for me. Code is in [client.py](https://github.com/Yelp/bravado/blob/0c538aaad96fa298a7d9a6018ed6100d3e60f117/bravado/client.py#L187).
