### ISSUE TITLE
Contributing an urllib2 http client

### ISSUE THREAD

**Issue by DanielJomphe** [Yelp/bravado#154]
We can't use either of the provided Fido and Requests clients, so I coded an urllib2 client.

Is that something you'd like to see contributed in this package?

PS congrats on releasing :sparkles:1.0.0:sparkles:!

**Comment by bpicolo** [comment]
@DanielJomphe Out of curiosity, what's the issue with Requests client?

**Comment by analogue** [comment]
I can't imagine adding support for the urllib2 client unless there is some feature that it has not already covered by the requests library.

**Comment by DanielJomphe** [comment]
Obviously, Requests is a very nice improvement over urllib2.

@bpicolo: compat with sandboxed python VMs (think GAE).

@analogue: no pressure on you, and no offense taken by a refusal: we can maintain that on our side as our own in-house, internal contrib.

**Comment by bpicolo** [comment]
Feel free to open source it if you'd like @DanielJomphe
