### ISSUE TITLE
Add allow_null option

### ISSUE THREAD

**Issue by jpizarrom** [Yelp/bravado#172]
add allow_null like in https://github.com/Yelp/bravado/pull/36

**Comment by alertedsnake** [comment]
Or at least figure out another workaround - it's very common to have database-backed data which has Nulls, that end up being None in Python, and then we get this:

jsonschema.exceptions.ValidationError: None is not of type 'string'

**Comment by zroadhouse-rmn** [comment]
I ran into this today, but in connection to null object values. My workaround was to monkey patch bravado_core like so:
~~~
# Monkey patch bravado to work around null object values
import bravado_core.unmarshal
old_unmarshal_object = bravado_core.unmarshal.unmarshal_object


def _unmarshal_object(swagger_spec, object_spec, object_value):
    if object_value is None:
        return None
    return old_unmarshal_object(swagger_spec, object_spec, object_value)

bravado_core.unmarshal.unmarshal_object = _unmarshal_object
# End monkey patch
~~~

**Comment by sjaensch** [comment]
The solution here is to use the [x-nullable property](http://bravado-core.readthedocs.io/en/latest/models.html#allowing-null-values-for-properties).

**Comment by zroadhouse-rmn** [comment]
Thank you! Definitely no need to monkey patch then.

**Comment by zroadhouse-rmn** [comment]
@sjaensch - has a version been released since https://github.com/Yelp/bravado-core/pull/64 was merged?

In bravado_core-4.3.0 there is no support in the unmarshal code path for x-nullable.

**Comment by zroadhouse-rmn** [comment]
I'm working on a PR with test cases. I can open a new ticket once I have it ready.

**Comment by sjaensch** [comment]
Great @zroadhouse-rmn! This looks like a bug indeed, I would have taken a look later this week. But a PR would be highly appreciated.

**Comment by zroadhouse-rmn** [comment]
PR is ready with test cases. :)
