### ISSUE TITLE
Question: handling of $ref:s to external .yaml files

### ISSUE THREAD

**Issue by tinnet** [Yelp/bravado#211]
I already had quick discussion with @sjaensch about this. The swagger spec allows both _.json_ and _.yaml_ files as [external `$ref`s](http://swagger.io/specification/#referenceObject).

Bravado currently does not support this, since `$ref`-loading is done by the `jsonschema` library (via `swagger_spec_validator`) as far as I can tell.

Obviously that library has no interest to support loading _.yaml_ files. Now the question is, where would be the place to fix this? Should `bravado` reimplement loading external refs for the yaml path? Should `swagger_spec_validator`?

_edit_: to clarify, the question I'm asking myself (and you guys) is: Where is the correct place to implement the loading of external yaml `$ref`s?

**Comment by striglia** [comment]
Relevant work we're in the middle of on pyramid_swagger https://github.com/striglia/pyramid_swagger/pull/164
