### ISSUE TITLE
$ref to local files

### ISSUE THREAD

**Issue by germanp** [Yelp/bravado#215]
I want to split my swagger spec file into multiple files. I've tried using the $ref but it seems to ignore the inclusion. Is referencing to a local file supported? I think that using the a full url path (with http://) works but does not serve me.

Thanks.

**Comment by analogue** [comment]
Yes, multiple files are supported. See https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md for examples.

**Comment by markfink** [comment]
link is broken :(
