### ISSUE TITLE
Python3 support for FidoClient

### ISSUE THREAD

**Issue by struys** [Yelp/bravado#223]
The FidoClient raises an exception if imported under python3:
```python
if six.PY3:
    raise ImportError("The fido client is not yet supported in py3")
```

I can't find documentation explaining why it doesn't support python3 so I figured i'd file this to get answer and start enumerating the blockers.

cc/@lucagiovagnoli @jnb

**Comment by lucagiovagnoli** [comment]
Mmh, I think that's a wider issue about Twisted not being python 3 ready. See this comment [on bravado](https://github.com/Yelp/bravado/blob/master/tests/fido_client/FidoClient/prepare_request_for_twisted_test.py#L20):
```python
@pytest.mark.skipif(
    six.PY3,
    reason="Fido client is not usable in py3 until twisted supports it",
)
```

Now that [Twisted is py3 ready](https://pypi.python.org/pypi/Twisted), it should not be hard to make fix this :)

**Comment by lucagiovagnoli** [comment]
https://github.com/Yelp/fido/pull/34
