### ISSUE TITLE
Should fido / twisted / requests be optional requirements?

### ISSUE THREAD

**Issue by asottile** [Yelp/bravado#227]
Or perhaps split out into separate packages?  To me it doesn't make too much sense to drag them along if they're not essential for functionality

**Comment by laucia** [comment]
They provide the networking capabilities, and that is what bravado brings on top of bravado-core.
So yes I think they are required.

Unless we want bravado not to be usable out of the box ?

**Comment by asottile** [comment]
but I can use bravado without using twisted or I can use bravado without using fido?

**Comment by lucagiovagnoli** [comment]
Sure, you can use bravado without using Fido (and hence Twisted) if you select the RequestClient. Or you can use bravado without using RequestClient if you select FidoClient. Bravado is the swagger-validation layer, it can use any http client, and we currently provide 2 of them out of the box

**Comment by asottile** [comment]
My suggestion is to split the specific implementations into other
packages.  If I'm just using, say, the twisted client then I really don't
care about fido, requests, and all their dependencies.  But currently
bravado requires me to install them.  If they're truly plug-and-play I see
no reason to put them in the core package.

**Comment by torwald-sergesson** [comment]
I think, it will be fine to move specific clients into another boxes. For example, bravado-fido-client, bravado-requests-client etc. Today I've tried to install bravado on CentOS 7 with python 3.5.2. And it was failed because of problems with twisted. But I'm not going to use twisted in my application, as fido client. I would prefer to install one more library, then to fix problems with twisted by forking.

**Comment by amilstead** [comment]
+1 to not including all of the implementation dependencies as part of Bravado's base installation. Separate packages isn't the only option, though -- maybe pick a default (perhaps `requests`) then include that as part of the main bravado dependency list and drop the others from the requirements file. The other implementations can stay in code but will raise `ImportError`s if they are used.

The `extras_require` feature from setuptools (documented [here](http://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords)) could be used to include other libraries dependent for the implementations that would now raise out on import.

**Comment by asottile** [comment]
seems this is no longer an issue
