### ISSUE TITLE
Should fetching swagger specs be done at buildtime instead of runtime?

### ISSUE THREAD

**Issue by struys** [Yelp/bravado#229]
The example usage of bravado suggests to fetch the spec via a url at runtime - https://github.com/Yelp/bravado#example-usage

There's a tradeoff doing this when you have many instances of a service with many web workers connecting to the same api - the number of requests to fetch the swagger spec is really high.

Is there a technical/philosophical reason why we don't suggest fetching the spec as part of building a service and then just load the spec from disk when a service starts? I understand we always want the specs to be up to date but that's only useful if the service making the api call needs to use the new functionality in which case they'd rebuild and redeploy anyways.

**Comment by striglia** [comment]
Definitely something that's been discussed before. I've got some thoughts
on this general subject bouncing around my head...I'll see if I can't pull
them together into something coherent and add it here :)

**Comment by analogue** [comment]
fyi, @jnb and @prat0318 discussed something similar (or was it exactly the same) with reasons for/against. maybe their findings were documented somewhere?

**Comment by struys** [comment]
We've internally had discussions about this and it sounds like there isn't a huge objection to this, when we start working on it we'll make sure to update the documentation.
