### ISSUE TITLE
Passing multiple query parameters with same name

### ISSUE THREAD

**Issue by wasbazi** [Yelp/bravado#230]
From digging through the issues in this repository I found an a merged PR from when swaggerpy existed that allowed you to pass a string query parameter as an array so that you could generate this as a query parameter: `http://www.petstore.swagger.io?foo=bar&foo=foobar` https://github.com/Yelp/bravado/pull/24

It appears that you used to be able to pass parameters like this:
```
from bravado.client import SwaggerClient
client = SwaggerClient.from_url("http://petstore.swagger.io/v2/swagger.json")
pet = client.pet.getPetBySearch(foo=["bar", "foobar"]).result()
```

Now that throws this error:
```
self = <jsonschema.validators.create.<locals>.Validator object at 0x1122c9f60>, args = (['bar', 'foobar'],), kwargs = {}
error = <ValidationError: "['bar', 'foobar'] is not of type 'string'">

    def validate(self, *args, **kwargs):
        for error in self.iter_errors(*args, **kwargs):
>           raise error
E           jsonschema.exceptions.ValidationError: ['bar', 'foobar'] is not of type 'string'
```

Is this by design to no longer allow query parameters like this? Or would it be helpful for me to track down what's preventing passing query parameters like this?

**Comment by prat0318** [comment]
This is because Swagger 2.0 has a specific format if multiple values are to be allowed for a query param. If that format is not defined, multi values (array) will not be supported (and the array will be treated as a wrong type). You should use the type below if you expect multi values in your query param.

The third parah in [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#other-parameters) spec says:

> An optional query parameter of a string value, allowing multiple values by repeating the query parameter:

```json
{
  "name": "id",
  "in": "query",
  "description": "ID of the object to fetch",
  "required": false,
  "type": "array",
  "items": {
    "type": "string"
  },
  "collectionFormat": "multi"
}
```

**Comment by wasbazi** [comment]
Thanks so much, I must have missed this in browsing the swagger documentation and that fixed up the problem I was running into.
