### ISSUE TITLE
Documentation update. SwaggerClient.from_spec

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#240]
http://bravado.readthedocs.io/en/latest/advanced.html#loading-swagger-json-by-file-path

```
from bravado.swagger_model import load_file

client = SwaggerClient.from_dict(load_file('/path/to/swagger.json'))
```
AttributeError: type object 'SwaggerClient' has no attribute 'from_dict'

I think the documentation should say:
```
from bravado.swagger_model import load_file

client = SwaggerClient.from_spec(load_file('/path/to/swagger.json'))
```

**Comment by sjaensch** [comment]
Thanks for the report @bxm156!
