### ISSUE TITLE
Bravado decorators hide SwaggerClient.get_model()

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#246]
When using a bravado client wrapper with some of the bravado decorators, I'm unable to access my models:

```
decorated_client.get_model('MyModel')
*** TypeError: 'ZipkinResourceDecorator' object is not callable
```

I would have to go all the way up the stack to access this function (I'm using 3 decorators here):
```
# I can access it via:
decorated_client.client.client.get_model
<bound method SwaggerClient.get_model of SwaggerClient(http://localhost:13895/)>

# But not directly 
decorated_client.get_model
<bravado_decorators.zipkin_decorator.ZipkinResourceDecorator object at 0x7f421231dbe0>
```

**Comment by sjaensch** [comment]
@bxm156 This sounds like a bug in the bravado client wrapper, not in bravado itself, or am I missing something?

**Comment by bxm156** [comment]
Nope.. just a severe lack of coffee...
