### ISSUE TITLE
Better HTTP Exceptions?

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#252]
It would be nice to have a little more granular HTTP Exceptions, rather than just a single one.

All HTTPExceptions could inherit from the existing HTTPException class, but we could have ones like:

NotFoundHTTPException(HTTPException):
ForbiddenHTTPException(HTTPException):
GatewayTimeoutHTTPException(HTTPException):

It would be nice for when I'm catching different exceptions and trying to handle each one differently.

**Comment by macisamuele** [comment]
I like really much the idea ... it is going to be perfectly backcompatible and at the same time could provide a better experience in the handling of those cases.
So now the question is: want @bxm156 you to implement it? If yes it will be great, otherwise I could handle it. Just let me know

**Comment by bxm156** [comment]
@macisamuele: Sure I'll take it

**Comment by macisamuele** [comment]
@bxm156++

**Comment by bxm156** [comment]
Hi @macisamuele , can you give me write access to the repo so I can push my branch

**Comment by macisamuele** [comment]
Hi @bxm156 ... our process for adding new features is based on the Pull Request system.
So please fork the repo, add the branch and do a pull request for it (it would be great if you link also the issue in the PR).
Thanks a lot for your support
