### ISSUE TITLE
Changelog for 0.9.3 (+proposal)

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#255]
The changelog is missing an entry for 0.9.3. (Also its not on pypi)

I would like to propose we add a "Master" version to the changelog, above the version numbers. As developers commit changes, they can add a message to that section on what they added. When it comes time to release a new version, a maintainer renames that section with the version number, and adds a new blank Master section.

This is how the Django project does it. It makes it easier to remember what has changed when it comes time to release a new version.

**Comment by sjaensch** [comment]
That's a great idea, feel free to add one when you do a PR. Most people unfortunately don't think about it, so we add it for them. Maybe we'll get to a point where keeping track of all the improvements will be a problem, that would be awesome. 😊
