### ISSUE TITLE
Automatic PyPi deployment

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado#256]
Would be nice to setup our travis ci to automatically deploy to pypi when a tag on master is created.

**Comment by sjaensch** [comment]
This already happens internally. For Python's PyPI we would need to store credentials somewhere within travis, which is why we're currently not doing that. I'm instead trying to solve this by introducing a runbook.

**Comment by bxm156** [comment]
@sjaensch  Travis CI allows you to encrypt your Python PyPi credentials and store them in your travis.yml. Only travis can read that information for the specific repository, so its safe to include it in a public repo.

https://docs.travis-ci.com/user/encryption-keys/
