### ISSUE TITLE
http exception by status code causes AttributeError: str has no status_code

### ISSUE THREAD

**Issue by asottile** [Yelp/bravado#260]
See comments on:
https://github.com/Yelp/bravado/commit/87fa6813c7367a066eaa76db0dfad8483067aad4#diff-0a21d9158985f1ced07c9ef0ad7bb297

```
>       self.status_code = getattr(self.response, 'status_code')
E       AttributeError: 'str' object has no attribute 'status_code'
```

This may be bad testing code on our end.  Either way the `getattr` should be changed to just attribute access or to default to `None`

**Comment by bxm156** [comment]
Yes, this is my bad, it was meant to default to None originally.
