### ISSUE TITLE
Create request without swagger.json

### ISSUE THREAD

**Issue by pavolloffay** [Yelp/bravado#263]
Hello, 

Is it possible to create a http request without pointing to the swagger.json file? 

(I'm trying to use https://github.com/Yelp/swagger_zipkin)

Pavol

**Comment by macisamuele** [comment]
Hi @pavolloffay to use bravado you should initialize somehow the ``SwaggerClient``.

You can do that passing the URL of the ``swagger.json`` file (with [``SwaggerClient.from_url``](https://github.com/Yelp/bravado/blob/master/bravado/client.py#L91)) or passing the swagger specs dictionary (with [``SwaggerClient.from_spec``](https://github.com/Yelp/bravado/blob/master/bravado/client.py#L125)).
Once you get your SwaggerClient instance you can decorate it with the zipkin decorator as shown in the [README](https://github.com/Yelp/swagger_zipkin/blob/master/README.md).
