### ISSUE TITLE
SwaggerValidationError: discriminator (type) must be defined in properties

### ISSUE THREAD

**Issue by drmikecrowe** [Yelp/bravado#279]
Can anybody help me understand this error?  The swagger.json is auto-generated from their source code, so I'm trying to understand how this needs to be fixed so I can use bravado.  http://editor.swagger.io/#!/ appears to (mostly) load it, at least enough to generate a library.

swagger_spec_validator.common.SwaggerValidationError: discriminator (type) must be defined in properties
   
This is in this section of swagger.json:
```json
    "FacetMember" : {
        "type" : "object",
        "discriminator" : "type"                        <<--here
    },
```

JSON file located here:  https://api.squidsolutions.com/release/v4.2/swagger.json

My program is simply:

```python
    from bravado.client import SwaggerClient
    from bravado.requests_client import RequestsClient
    
    http_client = RequestsClient()
    http_client.set_api_key(
        'http://localhost:8889', 'xxxxxxxxxxxxxxxxxxx', param_name='access_token'
    )
    client = SwaggerClient.from_url(
        'http://localhost:8889/release/v4.2/swagger.json',
        http_client=http_client,
    )
    projects = client.projects.get().result()
```

**Comment by macisamuele** [comment]
Hey @drmikecrowe as far as I can see from the specs they looks invalid.
According to [Swagger Spec Definition](http://swagger.io/specification/):
> Adds support for polymorphism. The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. The property name used MUST be defined at this schema and it MUST be in the required property list. When used, the value MUST be the name of this schema or any schema that inherits it.

An example of polymorphic specs is available [here](https://github.com/Yelp/bravado-core/blob/master/test-data/2.0/polymorphic_specs/swagger.json).

If you would like to have additional information I would suggest you to reach http://swagger.io/forum/.

Please close the issue if it solved your issue or give us more hints on how we can help you!

**Comment by drmikecrowe** [comment]
Thanks @macisamuele -- that was the direction I needed
