### ISSUE TITLE
pattern with regex

### ISSUE THREAD

**Issue by Amedeo91** [Yelp/bravado#281]
I was trying to add pattern in the pattern swagger file to validate the format of my input, but I saw that the regex has not been evaluated.

What do you think about providing such functionality?

Regards,
Amedeo

**Comment by laucia** [comment]
Could you provide an example of the functionality? 
Are you talking about Patterned XXX like patterned objects https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects ? (as this is the only reference to regexes in the OpenAPI 2.0 spec)

**Comment by Amedeo91** [comment]
Hi,

sorry for the late replay.
The functionality is the follow:
"position":{
                            "pattern":"^\\S+$",
                            "type":"string"
                        }

The filed position above should be type string and respecting the regex ^\\S+$. At the moment it is not working.

Regards,
Amedeo

**Comment by Amedeo91** [comment]
In the yaml

position:
            type: string
            pattern: ^\S+$

**Comment by macisamuele** [comment]
Hello @Amedeo91 it's really interesting the fact that it is not working properly to you.
Could you attach to this thread a "code example" that is not working?
We rely on [JsonSchema](https://github.com/Julian/jsonschema/) for JSON validation and [here](https://github.com/Julian/jsonschema/blob/master/jsonschema/_validators.py#L152) is enforcing ``pattern`` validation.

**Comment by Amedeo91** [comment]
Hi all,

there was an issue on my code. Now it is working fine

Regards,
Amedeo
