### ISSUE TITLE
QUESTION:  

### ISSUE THREAD

**Issue by mikepietsch11** [Yelp/bravado#293]
How would one work with ResourceDecorators that contain a dash?  

I can create a client from_url and when debugging can see:

client
  resource-one
      operationone
      operationtwo
  resource-two
  
but when I try to actually write python code to use the client object like:
     print(client.resource-one) 

I get AttributeErrors

AttributeError: Resource resources not found. Available resources: resource-one, resource-two

I am guessing this has to do with the fact that - is not valid in variable/function naming.

Any suggestions?

**Comment by laucia** [comment]
You are going to have to use a trick: getattr (client, 'resource-one')

Le mer. 21 juin 2017 à 23:15, Mike Pietsch <notifications@github.com> a
écrit :

**Comment by mikepietsch11** [comment]
Well, yeah, I should have thought of that - total fog of programming on my part.
Thank you

**Comment by sjaensch** [comment]
But you raise a good point, we have similar issues with parameters that contain dashes (especially likely for header parameters). We might want to think about a nicer solution.

**Comment by mikepietsch11** [comment]
Especially since it is an even uglier issue when the created methods are looking for parameters that have a - in them.  
...method(param-name="foo") results in {SwaggerMappingError} param-name is a required parameter
and 
...method("foo") results in  __call__() takes exactly 1 argument(2 given)

any other thoughts?

**Comment by noahprince22** [comment]
Has a nicer solution here been implemented? Or is everyone using ` getattr (client, 'resource-one')`?
