### ISSUE TITLE
cannot test against foreign URL target once imported URL spec

### ISSUE THREAD

**Issue by openfly** [Yelp/bravado#298]
```   
    url = operation.swagger_spec.api_url.rstrip('/') + operation.path_name
    request = {
        'method': str(operation.http_method.upper()),
        'url': url,
        'params': {},  # filled in downstream
        'headers': request_options.get('headers', {}),
    }
```

basically it might be wise to setup the logic to check for a request_options.get('url', {}) style query.

**Comment by macisamuele** [comment]
Sorry @openfly ... could you add more context around your issue? I'm not getting what your problem is.
Thanks for understanding

**Comment by openfly** [comment]
I am loading a spec file ( somewhat successfully ).  Then I am trying to use the methods that exist having been loaded by bravado.  But bravado configures the requests client ( and seemingly every client ) to target API endpoints based on the from_url spec loader call.

If you load from file this ends up being defaulted to localhost.

There's no way to set a target URI for the API you want to test against.  As far as I can tell.

**Comment by openfly** [comment]
```
    # url = operation.swagger_spec.api_url.rstrip('/') + operation.path_name
    request = {
        'method': str(operation.http_method.upper()),
        'url': request_options.get('url', {}).rstrip('/') + operation.path_name,
        'params': {},  # filled in downstream
        'headers': request_options.get('headers', {}),
    }
```
this is a hack i threw together to test around it for now.

**Comment by openfly** [comment]
this is in : bravado/client.py

**Comment by macisamuele** [comment]
Just for clarification you are interested in changing the base api url for testing?
If so have you tried something similar to 
```python
from bravado.client import SwaggerClient
swagger_dict = {
    ....
}
swagger_url = ... 
client = SwaggerClient.from_spec(spec_dict=swagger_dict, origin_url=swagger_url)
# your test code
```
or similar to
```python
from bravado.client import SwaggerClient
swagger_dict = {
    ....
}
client = SwaggerClient.from_spec(spec_dict=swagger_dict)
client.swagger_spec.api_url = ... 
# your test code
```

**Comment by openfly** [comment]
nope haven't seen that documented anywhere.  I'll give it a whirl.

**Comment by openfly** [comment]
seems to work.
