### ISSUE TITLE
Resources created when tags have spaces are inaccessible

### ISSUE THREAD

**Issue by ritwik** [Yelp/bravado#307]
This issue is a mix of Bravado / Bravado core so I'm filing here but happy to move to Bravado core if that is more appropriate.

# Summary:
When a resource has tags which have spaces, e.g "contact activites", its operations become inaccessible in the generated swagger client, because they must be accessed with the space (which isn't possible in python).

# Background:
We use bravado to create a client for this swagger spec: http://api.cordial.io/docs/v1/api-docs.php
In that spec, there are some resources with two word names (e.g `contactactivities`, `messagetransports`). In that spec, the tags for these have spaces in them (`contact activities`, `message transports`). See snippets below:

```json
"/v1/contactactivities":{
            "get":{
                "summary": "Get Activity list",
                "operationId": "getActivityList",
                "tags":[
                    "contact activities"
                ],
  ...
```

```json
"/v1/messagetransports/{id}":{
            "get": {
                "summary": "Get a transport's properties",
                "operationId": "getsingletransport",
                "tags":[
                    "message transports"
                ],
  ...
```

When we build a swagger client from this spec using bravado, we can't access those resouces:
```python
client = SwaggerClient.from_spec(
    CORDIAL_SPEC,
    http_client=http_client,
)
client.contactactivities.getActivityList() # Raises exception.
client.contact_activities.getActivityList() # Raises exception.

# Example exception (with some noise removed):
# ...
# File "../sales/coupons.py", line 256, in _send_to_cordial
#    client.contactactivities.addActivity(a="gotCoupon", email=email,
#  File "../lib/thirdparty/bravado/client.py", line 161, in __getattr__
#    .format(item, ', '.join(dir(self))))
# AttributeError: Resource contactactivities not found. Available resources: account attributes, account lists, automation templates, batch messages, contact activities, contact exports, contact imports, contacts, jobs, message content includes, message transports, orders, productimports, products, supplements
```

The exceptions happen because (from what I understand so far):
- `client.<anything>` works by overriding `__getattr__(self, attr)` to look up `attr` inside the resources dictionary
- bravado_core builds the resources dictionary from the tags if they exist. This means that for this spec, the dictionary has: `contact activities` and `message transports` as keys. 
- There's no way to access those without manually calling `__getattr__`. e.g It works if I do: `client.__getattr__("contact activities")`, but it seems wrong to directly access that as a user of the client.

Unfortunately I don't control the spec, so we can't just add more tags that are accessible.

# Suggestions
- Could the bravado_core create _'d versions of tags with spaces? That way you would have both `contact activities` and the accessible `contact_activities` in the resources dict. 
- Could the swagger client implement `__getitem__` so that `client["contact activities"]` works? This feels less semantically correct but is a workaround rather than directly calling the private function.
- Could bravado_core create resources for the tags and also the path its on (which I imagine is the behaviour when there's no tags). That way `.contactactivities` would work too.

I'm no expert on Swagger (this is my first API using it that I'm connecting to), so I'm unclear whether the tags property is meant to be used for creating the client resources. If it is, I can ask the spec authors to add more tags. But if not, they aren't obliged to tag things in a way my client will handle. Ideally bravado creates clients that match the API endpoints whether there are tags or not? 

If this is missing information that would be useful, happy to add more. Also, I'm happy to create a PR with what I think would help, but just want to make sure (as a first time contributor) that the general suggestion is reasonable (and perhaps, which one would be preferred).

**Comment by jakul** [comment]
I have the same problem. It's nicer to include spaces in the tags for display using Swagger UI, but that means that the API isn't callable from bravado.

Another solution (possibly requiring less debate) would be to implement a `client.get_resource('Tag Name')` method which we could use explicitly when the tags have spaces in

**Comment by jakul** [comment]
As a workaround you can do:

```
getattr(client, 'contact activities')
```

**Comment by macisamuele** [comment]
@jakul , @ritwik : what about using ``client.swagger_spec.get('Tag Name')``? It's already supported by bravado / bravado-core .
An other approach could be to open an issue within bravado-core project in order to sanitize the resource name before saving it using something like https://github.com/Yelp/bravado-core/blob/8ac640ce8cbd83272897a3b3ce25954971b3074b/bravado_core/operation.py#L133-L138

**Comment by jakul** [comment]
That example doesn't work for me - `AttributeError: 'Spec' object has no
attribute 'get'`

Either way the returned object needs to be an instance of
`ResourceDecorator` in order to be used like the other attrs on the client.





Em qua, 11 de out de 2017 às 11:57, Samuele Maci <notifications@github.com>
escreveu:

**Comment by jakul** [comment]
Fixing in bravado code is probably a better option. I didn't realise it was
already modifying the tag name. Doing one extra modification won't cause
any problems.

Em qua, 11 de out de 2017 às 12:39, Craig Blaszczyk <masterjakul@gmail.com>
escreveu:

**Comment by macisamuele** [comment]
@jakul your right ... writing it I missed an important part :) ``client.swagger_client.resources.get(...)``.
This is a possible workaround, similar to the you suggested above.

The code that I linked is related to operation_id but we could replicate the same logic for resource name too.
Please open an issue there and a PR if you have time, I don't know exactly if I could handle that in a timely manner.

**Comment by ritwik** [comment]
@jakul @macisamuele Thanks for the suggestions! I'm travelling this month so won't be able to test these out / create the PR (if needed) right away - but will do so when I'm back at work. Appreciate the assistance :)

**Comment by jakul** [comment]
@macisamuele `client.swagger_client.resources.get(...)` isn't a complete workaround, as the returned object needs to be wrapped in a `ResourceDecorator`, e.g.

```
from bravado.client import ResourceDecorator

ResourceDecorator(client.swagger_spec.resources.get('Some Tag')).api_action().result()
```

**Comment by jakul** [comment]
I've made a PR to fix the resource names to make sure they are valid Python identifiers in Bravado Core - https://github.com/Yelp/bravado-core/pull/200. I'm not sure if both of my PRs are needed, or if it's best to only fix this in Bravado Core or to only fix it in Bravado.
