### ISSUE TITLE
Implement environment merge capability for requests sessions

### ISSUE THREAD

**Issue by PascalVA** [Yelp/bravado#311]
Bravado requests throws an SSL: CERTIFICATE_VERIFY_FAILED error while requests is working.
I have tested this with bravado 9.0.0 and 9.1.0.
> bravado (9.1.0)                                                                                                                                                                               
> bravado-core (4.8.0)
> requests (2.18.4)

   * I have added the certificate in question to the Debian ca-certificates and it is also working in curl
   * I have exported the REQUESTS_CA_BUNDLE environment variable (this fixed it for using requests, but not for bravado)

I don't know if it could be relevant, but the kubernetes certificate validates multiple names.
(kubernetes, kubernetes.default, kubernetes.default.svc,...)

## Expected Result
And "Unauthorized" HTTP response from the kubernetes API.

## Actual Result
Bravado throws a requests exception:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "py/vendor/openapi/client.py", line 46, in clientCallableOperationCallHook
>     return httpFuture.result() # HACK automatically call .result()
>   File "/usr/local/lib/python2.7/site-packages/bravado/http_future.py", line 71, in result
>     inner_response = self.future.result(timeout=timeout)
>   File "/usr/local/lib/python2.7/site-packages/bravado/requests_client.py", line 289, in result
>     timeout=self.build_timeout(timeout),
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kubernetes.default.svc', port=443): Max retries exceeded with url: /api/v1/namespaces/namespace/services/name (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))

## Reproduction Steps
The following excerpts were all ran in the same interactive python session
```python
import requests
requests.get("https://kubernetes.default.svc")
<Response [401]>
requests.get("https://kubernetes.default.svc").text
u'Unauthorized\n' 

import os; import bravado_client; import yaml
with open('py/vendor/kubernetes/kubernetes.openapi.json', 'r') as f:
  specification = yaml.load(f.read())

config = {'validate_swagger_spec': False, 'use_models': False, 'validate_requests': False, 'validate_responses': False}
httpClient = bravado.requests_client.RequestsClient()
openapiClient = bravado.client.SwaggerClient.from_spec(specification, config=config, http_client=httpClient, origin_url=os.environ.get('KUBERNETES_URL'))
result = openapiClient.core_v1.readCoreV1NamespacedService(name="name", namespace="namespace").result()
Traceback (most recent call last):   
  File "<stdin>", line 1, in <module>                                      
  File "/usr/local/lib/python2.7/site-packages/bravado/http_future.py", line 71, in result                                                            
    inner_response = self.future.result(timeout=timeout)                   
  File "/usr/local/lib/python2.7/site-packages/bravado/requests_client.py", line 289, in result                                                       
    timeout=self.build_timeout(timeout),                                   
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send                                                               
    r = adapter.send(request, **kwargs)                                    
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send                                                               
    raise ConnectionError(e, request=request)                              
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kubernetes.default.svc', port=443): Max retries exceeded with url: /api/v1/namespaces/namespace/services/name (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))                 
```

**Comment by PascalVA** [comment]
After looking into the Bravado code some more, I've noticed Bravado is using requests Session objects. I can reproduce the problem by using just requests Session objects.

```python
import requests
requests.get('https://kubernetes.default.svc')
<Response [401]>
request = requests.Request('GET', 'https://kubernetes.default.svc')
prepared_request = request.prepare()
response = s.send(prepared_request)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kubernetes.default.svc', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
```

Closing this issue.

**Comment by PascalVA** [comment]
Using requests sessions do not take into account the environment. The environment has to explicitly be merged (see: https://github.com/requests/requests/issues/4256).

This merge should probably be implemented in Bravado, or at least an option to do so.
I would be happy to create a PR.

```python
from requests import Request, Session
s = Session()
req = Request('GET', 'https://kubernetes.default.svc')
prepped = s.prepare_request(req)
settings = s.merge_environment_settings(prepped.url, None, None, None, None)
resp = s.send(prepped, **settings)
print resp.status_code
> 401
```

**Comment by PascalVA** [comment]
I never got any response on my request to do a PR, so we solved it by overwriting the requestsFutureAdapterRestulHook directly in our openapi client.

I will definately give your solution a try!

**Comment by bedge** [comment]
I need both, @bwalsh's fix for client cert authentication and the option to use verify=False to the requests layer to disable server cert validation.
Without both of these it's just not adaptable to the variety of dev/qa/prod instance one needs.

**Comment by macisamuele** [comment]
Hello all ... sorry for the super late reply.
I would say that the raised issue is valid and worthy to be addressed, unfortunately I have no bandwidth to do that in the next weeks.
@PascalVA could you still publish a PR addressing the issue?

**Comment by PascalVA** [comment]
Hey,

I will try to make some time for it soon. I tried to setup a clean venv with dev requirements yesterday, but the tests kept failing.
