### ISSUE TITLE
How to inspect a request before is sent?

### ISSUE THREAD

**Issue by lcofre** [Yelp/bravado#312]
Hi!

While executing a request I am getting a 401 response from my api when I am expecting a 200, so I was wondering if it's possible to see how the request was built before it was sent.

The request I am testing has a parameter in the path, another in the body, and the authentication as a query param. Something like this (though the definition is not complete):

```
  /resources/{id}:
    patch:
      summary: Changes properties on the resource
      tags:
        - resource
      parameters:
        - name: id
          in: path
          description: resource id
          required: true
          type: string
        - name: resourceProperties
          in: body
          required: true
          schema:
            $ref: '#/definitions/ResourceProperties'
      security:
        - Token: []
      responses:
        200:
          $ref: '#/responses/Successful'
        400:
          $ref: '#/responses/Error'
        401:
          $ref: '#/responses/UnknownUser'
definitions:
  ResourceProperties:
    type: object
    properties:
      property1:
        type: boolean
        description:  The property to change
securityDefinitions:
  Token:
   type: apiKey
   in: query
   name: token
```

And I call the api like this
```
api = SwaggerClient.from_url('path/to/swagger/definition.yaml', config={'use_models': False, 'also_return_response': True})

msg, r = api.resource.patch_resources_id(id='...', resourceProperties={'property1': True}, token='...').result()
```

Thanks very much for your help!

**Comment by macisamuele** [comment]
@lcofre I would suggest you to ways:
1. set a breakpoint in your code before calling ``result`` method on the future object and follow the code up to [``self.session.send``](https://github.com/Yelp/bravado/blob/v9.1.0/bravado/requests_client.py#L287)
2. create your own Client extending ``RequestClient`` and your own ``FutureAdapter`` that replicates ``RequestsFutureAdapter.result`` logic which injects additional logging informations.

Hope that this helps you.
I'm closing it ... but feel free to reopen it if you need more support

**Comment by lcofre** [comment]
Thanks for the answer!

To make it easy I inspected the request when it arrives to the server.

**Comment by macisamuele** [comment]
@lcofre  that's even possible ... but I was not sure that you had access to it 😄
