### ISSUE TITLE
Can't parse spec file from Jupyter

### ISSUE THREAD

**Issue by mikepurvis** [Yelp/bravado#327]
The errors are opaque enough that I don't really know where to begin, but neither `from_url` or `from_spec` was able to do the right thing. See https://github.com/jupyter/jupyter/issues/297.

**Comment by macisamuele** [comment]
@mikepurvis reading the linked issue I see that you're trying to initialize the client using ``SwaggerClient.from_url('http://localhost:8888/api/spec.yaml')``.
While invoking ``from_url`` bravado will fetch the swagger spec file (yaml file in your case), read it and initialize the ``bravado-core`` ``Spec`` object.

According to the reported stack trace I see that ``pyyaml`` library is failing in decoding the yaml content.
Is possible that the file returned by your URL is not a valid yaml file?
If so I guess that you fixed your problem, if you think that the file is correct I would suggest to look into known issues of [``pyyaml``](https://github.com/yaml/pyyaml) or at least give us information about the file content (if possible).

The main difference of the init methods is:
 * ``from_spec`` expects the swagger specs in python dictionary format
 * ``from_url`` fetches the swagger specs from a url (like in your case), decode them into python dictionary and call ``from_spec``

**Comment by macisamuele** [comment]
I've tried also to fetch the jupyter swagger specs from their [github repo](https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml).
```python
from bravado.client import SwaggerClient
client = SwaggerClient.from_url('https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml')
# This is needed otherwise your api calls will be redirected to https://raw.githubusercontent.com/api
client.swagger_spec.api_url = 'http://localhost:8888/api'

# Example of api call
response = client.config.get_config_section_name(section_name='test').result(timeout=1)
```

**Comment by mikepurvis** [comment]
Oh, blah, I see what's going on here— the `api/spec.yaml` path in Jupyter requires authentication, so it was returning a blank 403 page that Bravado was attempting to parse as yaml. I should have clued into that sooner. There's probably a bug on both sides there, in that Bravado should warn when a supplied spec URL returns an error code and/or empty page, and Jupyter should serve the API spec without authentication req'd.

That said, it's weird then that this (https://github.com/jupyter/jupyter/issues/297#issuecomment-342281629) didn't work, where I parsed myself a pre-downloaded version of the yaml and then just passed that into Bravado:

```
import yaml
from bravado.client import SwaggerClient
client = SwaggerClient.from_spec(yaml.load(open('api.yaml')))
```

So this is workable for me—the `.yaml` suffix is required, or Bravado assumes JSON and fails to parse, haha:

```
from bravado.client import SwaggerClient
TOKEN = 'xxxxxxxxxxx'
client = SwaggerClient.from_url('http://localhost:8888/api/spec.yaml?token=%s&.yaml' % TOKEN)
```

Thanks for the quick response and digging in. Much appreciated.

**Comment by macisamuele** [comment]
Could you save the content of the generated spec into a gist.github.com ? It makes me curious the [``swagger_spec_validator``](https://github.com/Yelp/swagger_spec_validator) validation issue.

**Comment by mikepurvis** [comment]
Oh! I'm pretty sure that was a legit validation failure as a result of missing https://github.com/jupyter/notebook/commit/b0205c4b78829f1e51b385bd62d8cff64d42a423.

**Comment by macisamuele** [comment]
@mikepurvis definitely that was the case I see ``items: {"$ref": "#/parameters/section_name"}``.
Thanks 👍

**Comment by mikepurvis** [comment]
Okay, I gave bravado another try, but I think I really am going to go back to the code generator for now. Some further issues:

- I found it difficult to discover the method names and parameters— the RTD page encouraged me to explore in the REPL, which I did using `help()` and `dir()`, but most of the time I was looking at the pydoc for `ResourceDecorator` or some other internal infrastructure, not actual API documentation. At least with the codegen option I'm able to view the source to understand the implementation.
- When I tried to actually call APIs, I got opaque and confusing errors, for example:

```
>>> notebook.client.contents.get_contents_path('Untitled.ipynb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes exactly 1 argument (2 given)

>>> notebook.client.contents.get_contents_path(path='Untitled.ipynb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/bravado/client.py", line 261, in __call__
    config['also_return_response'])

>>> client = SwaggerClient.from_url('path/to/api.yaml', config={'also_return_response': False})
>>> client.swagger_spec.api_url = 'http://localhost:8888/api'
>>> notebook.client.contents.get_contents_path(path='Untitled.ipynb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/bravado/client.py", line 261, in __call__
    config['also_return_response'])
KeyError: 'also_return_response'
```

Anyway, I appreciate again your time helping me to get going, I like the idea behind this project, but I don't think it's the right fit for me at the moment.
