### ISSUE TITLE
Default parameters are not unmarshalled correctly

### ISSUE THREAD

**Issue by benfiola** [Yelp/bravado#350]
Long story short, I'm trying to use bravado to auto-generate a client around a versioned API.

Let's say I have these endpoints.

```
/api/ping?version=1.0.0
/api/ping?version=2.0.0
```

When a user requests a swagger spec, they might ask for something like`/api/swagger/json/2.0.0`, which will give them something like so:

```
{
  "basePath": "/api", 
  "definitions": {}, 
  "info": {
    "title": "service", 
    "version": "2.0.0"
  }, 
  "parameters": {}, 
  "paths": {
    "/ping": {
      "get": {
        "description": "Ping 2.0 endpoint", 
        "parameters": [
          {
            "default": "2.0.0", 
            "in": "query", 
            "name": "version", 
            "type": "string"
          }
        ], 
        "responses": {
          "200": {}, 
          "400": {}, 
          "401": {}, 
          "404": {}
        }
      }
    }
  }, 
  "swagger": "2.0", 
  "tags": []
}
```

The goal here is to have the user specify up front that they want to use a specific version of the API and no longer need to provide the version as an argument to every API that they call through bravado.

However, I'm finding the following behavior happening:

If the `version` parameter is set to default and the user specifies the version manually when invoking the `Operation`, everything works fine.

If the `version`parameter is set to default, and the user doesn't specify the version manually when invoking the `Operation`, the parameter never gets unmarshalled - this is because of the following block of code located in `bravado_core.param.marshal_param:116`:

```
    # Rely on unmarshalling behavior on the other side of the pipe to use
    # the default value if one is availabe.
    if value is None and not schema.is_required(swagger_spec, param_spec):
        return
```

In a last ditch effort to see if I can work around this, I tried specifying that this parameter has both a default value and is required (I'm aware that this is ambiguous in the swagger spec to my understanding), but despite this, setting the parameter to required results in an exception thrown in `bravado.client.construct_params:317` through the following code block:

```
    # Check required params and non-required params with a 'default' value
    for remaining_param in itervalues(current_params):
        if remaining_param.location == 'header' and remaining_param.name in request['headers']:
            marshal_param(remaining_param, request['headers'][remaining_param.name], request)
        else:
            if remaining_param.required:
                raise SwaggerMappingError(
                    '{0} is a required parameter'.format(remaining_param.name))
            if not remaining_param.required and remaining_param.has_default():
                marshal_param(remaining_param, None, request)
```

As I'm seeing it default parameters only get unmarshaled if they're required.  However, setting them to required will trigger an exception (because they don't have a value provided manually by the end user earlier in the code path) - if my understanding of the logic is correct, it looks like default parameters that don't have a manual value appear to never get unmarshaled.  If this is the case, and this isn't what it's supposed to do, I can put up a quick PR to fix this - otherwise, is there any workaround I can use to get this working?

Thanks!

**Comment by bdowling** [comment]
@benfiola I think you've fallen victim to the `default parameters trap`.  In openapi, the 'default' values are what is assumed by the API.  The comment above is saying the other end of the pipe, meaning the server will assume the default values if they were provided.  Bravado (or any other openapi client) does not inject those spec defaults into your query, it skips them to save bandwidth.  You'll need to find some other way to provide the versioning to your service, such as through the static paths or basePath.

**Comment by benfiola** [comment]
Hey @bdowling - thanks for responding!  Sounds reasonable enough - I'll close this for now.
