### ISSUE TITLE
set_api_key is not working

### ISSUE THREAD

**Issue by lunne** [Yelp/bravado#389]
Hi,
```
http_client = RequestsClient()
http_client.set_api_key(
    'api.yourhost.com', 'token',
    param_name='api_key', param_in='query'
)
client = SwaggerClient.from_url(
    'http://petstore.swagger.io/v2/swagger.json',
    http_client=http_client,
)
pet = client.pet.getPetById(petId=1).response().result

```
It doesn't seems like this adds anything to the request.
![image](https://user-images.githubusercontent.com/7102889/46019286-07bd8880-c0dc-11e8-81ba-f5a343fee703.png)

Thats a dump from the package going from the client. the uri should be &api_key=token ?
I have tried with headers also and its **not** setting that in the requests either.

so the set_api_key doesn't seem to work.

**Comment by lunne** [comment]
This is not an issue.. I looke through the code and found that paramter host='api.yourhost.com' must be set to the host of the API. :)

**Comment by JoshuaC3** [comment]
@lunne is that the base url or the auth url? May you give an example? Many thanks.

**Comment by uniqueg** [comment]
@JoshuaC3: Bit late, but I just had the same problem so I should I'd share:

You need to pass the root URL without schema and path as is given in the example (`api.yourhost.com`).

Another example:

- Full URL to your API: `https://my.api.info/v1/some-endpoint`
- What to supply to the `path` param: `my.api.info`

Full usage:
```py
from urllib.parse import urlparse

from bravado.client import SwaggerClient
from bravado.requests_client import RequestsClient

schema_url='http://petstore.swagger.io/v2/swagger.json'
token="S0MeT0kEn"

http_client = RequestsClient()
http_client.set_api_key(
    host=urlparse(schema_url).netloc,
    api_key=f"Bearer {token}",
    param_name="Authorization",
    param_in="header",
)
client = SwaggerClient.from_url(
    schema_url,
    http_client=http_client,
)
request = client.pet.getPetById(petId=1)

# Verify that Authentication header is in headers dict
print(request.future.request.headers)
```
