### ISSUE TITLE
final readthedocs quickstart example not producing expected result

### ISSUE THREAD

**Issue by ras44** [Yelp/bravado#420]
The final example at:
https://bravado.readthedocs.io/en/stable/quickstart.html

https://github.com/Yelp/bravado/blame/master/docs/source/quickstart.rst#L94-L110

does not seem to produce a dict.  `print(type(result))` shows an object of the same class as the first example's result: `<class 'abc.Pet'>` and `print(result)` is:

['category', 'id', 'name', 'photoUrls', 'status', 'tags']

**Comment by sjaensch** [comment]
This works for me, are you sure you passed `config={'use_models': False}` to `SwaggerClient.from_url()`?

**Comment by ras44** [comment]
Indeed.  It works now.  My apologies!
