### ISSUE TITLE
Add setup_requires or a requirements.txt to improve pip installs.

### ISSUE THREAD

**Issue by JoshuaC3** [Yelp/bravado#424]
On occasions, when installing bravado into a directory using pip, the requirements are not installed to the directory. After some searching, I found [this](https://stackoverflow.com/questions/35516059/python-is-not-installing-dependencies-listed-in-install-requires-of-setuptools) which hints a package would benefit from having these listed in the `setup_requires` as well as `install_requires` in the `setup.py` file. This [SO question](https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py) highlights that having `setup_requires` is useful when redistributing the package. This is the use case I have; I am trying to use bravado in an AWS Layer to work with AWS Lambda.

Alternatively, having a `requirements.txt` instead of listing deps in `setup.py` would also address this issue.

**Comment by sjaensch** [comment]
As was pointed out in a comment to the SO answer, `setup_requires` is for dependencies as install time while `install_requires` is for runtime dependencies. As the other SO answer pointed out, more likely than not the issue for the person asking the question was related to them providing a `cmdclass` argument.

Either way, this is not a bug in bravado - doing `pip install bravado` _will_ install all required dependencies. Please either provide specific steps to reproduce, or file a bug with AWS Lambda if they do not honor requirements specified in setup.py.

**Comment by JoshuaC3** [comment]
Point taken. Thanks for clarifying.
