### ISSUE TITLE
cannot create SwaggerClient from https URL

### ISSUE THREAD

**Issue by williehallock802** [Yelp/bravado#443]
The error I am getting is:

`HTTPSConnectionPool(host='10.10.8.142', port=8088): Max retries exceeded with url: /v2/api-docs (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))`

Now, I assume this is because I need to find a way to pass along the certificate needed to authenticate with the https server, but I am not sure how to do that with Bravado and my google searches haven't turn up anything.

**Comment by sjaensch** [comment]
I assume you're using the default HTTP client. In that case pass a `RequestsClient` instance when you create your `SwaggerClient`, and either disable SSL verification or provide the certificate. You can find more information in the [documentation](https://bravado.readthedocs.io/en/stable/configuration.html#customizing-the-http-client),
