### ISSUE TITLE
RPM Packaging

### ISSUE THREAD

**Issue by micahculpepper** [Yelp/bravado#452]
Hello folks,

Would you be willing to publish RPMs of Bravado in addition to the Python packages you already provide? I've got an application where I would like to use Bravado, but due to restrictions on the environment, I can't install dependencies with pip; I have to use yum.

**Comment by sjaensch** [comment]
Hey @micahculpepper, that's a very specific request. Feel free to submit a PR that adds support for it - that's the beauty of open source!

Are you sure you need RPMs? Using virtualenv you should be able to install your package just fine. Have you looked into that? Or do you need a system-wide install?
