### ISSUE TITLE
Plans for a new major version of Bravado (e.g. based on Hip)?

### ISSUE THREAD

**Issue by twosigmajab** [Yelp/bravado#453]
First off, thanks for maintaining Bravado! Just started looking at it, and so far it looks like the best basis for generating Python clients for OpenAPI-enabled services.

When I see all these [HttpFuture](https://github.com/Yelp/bravado/blob/28700d2a4bb19736307fecf7b8e35684c6f2d31d/bravado/http_future.py#L133)-style APIs, I can't help but ask if you've read [this post](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/) and have given any thought yet to basing a future version of Bravado on https://github.com/python-trio/hip? (Started as an async-first fork of urllib3 by the author of Trio, but the urllib3 maintainer has moved to co-maintaining Hip for the future async HTTP Python client to rule them all.)

**Comment by sjaensch** [comment]
For now we're not in a position to drop Python 2 support. We're also not in a position to require all bravado users to change the way they use bravado, e.g. by requiring them to use a context manager as well.

That said, if you're interested in developing such a version of bravado, please go ahead and do it!
