### ISSUE TITLE
Question: How to increase connection pool?

### ISSUE THREAD

**Issue by ErikKalkoken** [Yelp/bravado#459]
We are using bravado in our Django app to provide access to an API and it works great so far.

Now we would like to use one bravado client with multiple parallel threads (celery with gevent). But when running with about 30 threads for some time we are getting warnings that the connection pool is exhausted:

```plain
[2020-04-15 23:44:53,585: WARNING/MainProcess] Connection pool is full, discarding connection: esi.evetech.net
```

Our assumption is that the urllib connection pool that bravado uses has less connections than the number of threads we are running (e.g. 30 in our test).

So my question is: Is there a way to configure the size of the urllib connection pool that bravado uses? This is with the normal SwaggerClient, not Fido.

Any help would be very much appreciated!

**Comment by analogue** [comment]
Looks like the connection pool configuration is a few layers deep (may not be exact):
```
client:SwaggerClient -> http_client:RequestsClient -> session:requests.Session -> adapters:Dict[prefix:str, adapter:RequestsAdapter]
```

You can create an instance of an [HTTPAdapter](https://github.com/psf/requests/blob/master/requests/adapters.py#L84) passing in your connection pool settings to the constructor.  

To use your HTTPAdapter instance, do something like 
```
client.http_client.session.mount('http://', myHttpAdapter)
```
  
This should be enough to get you going down the right path.

**Comment by ErikKalkoken** [comment]
Took me a while to implement, but I can now confirm that it works. Thanks for your help!
