### ISSUE TITLE
follow_redirects config option seems to have no effect

### ISSUE THREAD

**Issue by amancevice** [Yelp/bravado#461]
I am attempting to create a Swagger client that follows redirects but I am not seeing the behavior I would expect (it raises `HTTPFound: 302 Found`)

Here is essentially what I am trying to do:

```python
from bravado.client import SwaggerClient

client = SwaggerClient.from_url('https://my.swagger.endpoint/', config={'follow_redirects': True})
client.resource.example().response()
# BOOM!
```

**Comment by sjaensch** [comment]
Note that this is a [per-request configuration option](https://bravado.readthedocs.io/en/stable/configuration.html#per-request-configuration), so you'll have to pass it differently. To reuse your example:

```py
from bravado.client import SwaggerClient

client = SwaggerClient.from_url('https://my.swagger.endpoint/')
client.resource.example(_request_options={'follow_redirects': True}).response()
```

**Comment by amancevice** [comment]
ah cool, thanks.
