### ISSUE TITLE
How do I make a request with a sanitizing name `async`?

### ISSUE THREAD

**Issue by george-kuanli-peng** [Yelp/bravado#491]
How do I make a request with a sanitizing name `async`?
`async` is a Python reserved keyword and cannot be used in keyword arguments.

**Comment by george-kuanli-peng** [comment]
Workaround: pass the "asyc" parameter with a dictionary and unpack the dictionary with `**`.

**Comment by macisamuele** [comment]
Yeah... Unfortunately the mentioned workaround is the only option available.
Closing this as a solution to the issue has been communicated already
