### ISSUE TITLE
Validate swagger specs against the swagger spec json schema

### ISSUE THREAD

**Issue by jnb** [Yelp/bravado#60]
The Swagger spec has a [json schema](https://github.com/wordnik/swagger-spec/tree/master/schemas).  We should validate downloaded specs against this schema to make it easier to detect any errors.

**Comment by dnephin** [comment]
I don't really think this is necessary.  The server side is responsible for validating the interface it exposes. If it's sending a bad spec the client isn't going to be able to do anything about it. We may as well just return a nice message when we fail to build the `Resource` and `Operation` objects. This happens at the same time (client instantiation). I don't think validating schemas buys us anything.

If we do this, we should make it optional and default to False.

**Comment by analogue** [comment]
This is implemented in bravado (Swagger 2.0) and swaggerpy (Swagger 1.2)
