### ISSUE TITLE
Sync requests can't actually be cancelled, so we shouldn't expose it

### ISSUE THREAD

**Issue by bpicolo** [Yelp/bravado#70]
It's a bit weird to have our single HTTPFuture that has methods that don't do anything for the synchronous case.

In addition, our "clients" are actually more of request factories at this point, so they don't really have the responsibility to wait or cancel the request.

See pull #69  for a bit of chat about this. We probably should rename our clients to factories and split up HTTPFuture for the cases it's used.

**Comment by dnephin** [comment]
But we do want to keep a consistent interface for both sync and async. So either we need to remove the ability to cancel an async request (which is probably ok), or we have to keep the sync.cancel.

**Comment by bpicolo** [comment]
It's true.

Fwiw, I've yet to see a case where we need to cancel one.

**Comment by prat0318** [comment]
I am working on refactoring the HttpClient's future interface for bravado. I am removing the `cancel()` methods from the interface, unless anyone objects to it. cc @analogue

**Comment by analogue** [comment]
This is done. 

https://github.com/Yelp/bravado/blob/master/bravado/http_future.py#L7
